version: '3'
services:
  db:
    image: postgres:11.4-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/plebs
    ports:
      - "3000:3000"
    depends_on:
      - db